#!/bin/bash
#   WARNING: This is an autogenerated script
#   Software Updater - autocompletion script
#
#      Copyright © 2017 Intel Corporation.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, version 2 or later of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


#declares the completion function
_swupd()
{
    # $1 is the command being completed, $2 is the current word being expanded
    local opts IFS=$' \t\n'
    local -i i installed
    COMPREPLY=()
    for ((i=COMP_CWORD-1;i>=0;i--))
    do case "${COMP_WORDS[$i]}" in
	    ("$1")
		opts=" -h --help -v --version bundle-add bundle-remove hashdump update verify check-update search"
	    break;;
	    ("bundle-add")
		opts="-h --help -u --url -c --contenturl -v --versionurl -P --port -p --path -F --format -l --list -x --force -S --statedir "
		break;;
	    ("bundle-remove")
		opts="-h --help -p --path -u --url -c --contenturl -v --versionurl -P --port -F --format -x --force -S --statedir "
		break;;
	    ("hashdump")
		opts="-h --help -n --no-xattrs -p --path "
		break;;
	    ("update")
		opts="-h --help -d --download -u --url -P --port -c --contenturl -v --versionurl -s --status -F --format -p --path -x --force -S --statedir "
		break;;
	    ("verify")
		opts="-h --help -m --manifest -p --path -u --url -P --port -c --contenturl -v --versionurl -f --fix -i --install -F --format -q --quick -x --force -S --statedir "
		break;;
	    ("check-update")
		opts="-h --help -u --url -v --versionurl -P --port -F --format -x --force -p --path -S --statedir "
		break;;
	    ("search")
		opts="-h --help -l --library -b --binary -s --scope -d --display-files -i --init -u --url -c --contenturl -v --versionurl -P --port -p --path -F --format -S --statedir "
		break;;
	esac
    done
    # Add in additional completion options if we need to
    if (( $i >= 0 ))
    then
	case "${COMP_WORDS[$i]}" in
	    ("bundle-add")
		if [ -r /var/lib/swupd/version ] &&
		       installed=$(</var/lib/swupd/version) &&
		       [ -r /var/lib/swupd/$installed/Manifest.MoM ]
		then
		    opts+="$( sed '1,/^$/d; s/^.*\t/ /' /var/lib/swupd/$installed/Manifest.MoM | LC_ALL=C sort )"
		fi ;;
	    ("bundle-remove")
		opts+=" $(unset CDPATH; test -d /usr/share/clear/bundles && \
			cd /usr/share/clear/bundles && ls | grep -v '^os-core' )"
		;;
	esac
    fi

    COMPREPLY=($(compgen -W "${opts}" -- ${2}));
    return 0
}
complete -F _swupd -o nosort swupd

