.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHECK\-UPDATE\.SERVICE" "4" "November 2016" "" ""
.
.SH "NAME"
\fBcheck\-update\.service\fR \- System Unit
.
.SH "SYNOPSIS"
\fBcheck\-update\.service\fR \fB/usr/lib/systemd/system/check\-update\.service\fR
.
.SH "DESCRIPTION"
Instructs the \fBsystemd(1)\fR system daemon how to start and control the \fBswupd\fR service to perform an update check\.
.
.P
When this unit runs, the output will be sent to the systemd journal, and it can be inspected with the \fBjournalctl(1)\fR command\.
.
.SH "ENVIRONMENT"
This unit is a \fBsystemd(1)\fR unit file\.
.
.SH "COPYRIGHT"
.
.IP "\(bu" 4
Copyright (C) 2016 Intel Corporation, License: CC\-BY\-SA\-3\.0
.
.IP "" 0
.
.SH "SEE ALSO"
\fBswupd(1)\fR, \fBcheck\-update\.timer(4)\fR
.
.SH "NOTES"
Creative Commons Attribution\-ShareAlike 3\.0 Unported
.
.IP "\(bu" 4
http://creativecommons\.org/licenses/by\-sa/3\.0/
.
.IP "" 0

