.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SWUPD\-UPDATE\.TIMER" "4" "November 2016" "" ""
.
.SH "NAME"
\fBswupd\-update\.timer\fR \- System Unit
.
.SH "SYNOPSIS"
\fBswupd\-update\.timer\fR \fB/usr/lib/systemd/system/swupd\-update\.timer\fR
.
.SH "DESCRIPTION"
Instructs the \fBsystemd(1)\fR system daemon when to periodically start a system software update\. The update itself may not execute if the \fBswupd\-update\.service(4)\fR is disabled\. See that manual page for information on how to disable that unit\.
.
.SH "ENVIRONMENT"
This unit is a \fBsystemd(1)\fR unit file\.
.
.SH "COPYRIGHT"
.
.IP "\(bu" 4
Copyright (C) 2016 Intel Corporation, License: CC\-BY\-SA\-3\.0
.
.IP "" 0
.
.SH "SEE ALSO"
\fBswupd(1)\fR, \fBswupd\-update\.service(4)\fR
.
.SH "NOTES"
Creative Commons Attribution\-ShareAlike 3\.0 Unported
.
.IP "\(bu" 4
http://creativecommons\.org/licenses/by\-sa/3\.0/
.
.IP "" 0

